sudo: required
dist: trusty
language: python
python:
  - 3.6

before_install:
  - sudo apt-get update -qq
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

install:
  - pip install numpy scipy pandas pytest nbformat nbconvert jupyter_client jupyter matplotlib pytest-xdist pytest-cov codecov nose nose-timer
  - pip install https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.4.0-cp36-cp36m-linux_x86_64.whl
  # Replace dep1 dep2 ... with your dependencies
  # - conda create -q -n test-environment python=3.5 numpy scipy pandas nose nbformat nbconvert jupyter_client jupyter matplotlib
  - git clone https://github.com/GPflow/GPflow.git
  - cd GPflow    
  - python setup.py install
  - cd ..
  - python setup.py install

script:
  - nosetests --with-coverage --nologcapture --nocapture --with-timer testing
  - codecov

cache:
  apt: true
  pip: true
  directories:
    - $HOME/.cache/pip
    - $HOME/download
